import type { MedicarePlan } from "@/types/medicare";

export const mockMedicarePlans: MedicarePlan[] = [
  {
    id: "mc-1",
    name: "Humana Gold Plus H5619-107 (HMO)",
    type: "MA",
    carrier: "Humana",
    premium_monthly: 0,
    deductible: 0,
    outOfPocketMax: 5900,
    starRating: 4.5,
    benefits: {
      primaryCare: "$0 Copay",
      specialist: "$35 Copay",
      emergencyRoom: "$120 Copay",
      urgentCare: "$40 Copay",
      rxCoverage: "$0 Tier 1-2",
      dental: "Included",
      vision: "$300/yr",
      hearing: "$500/yr",
    },
    highlights: ["$0 Monthly Premium", "Dental & Vision included", "$0 Tier 1 Rx"],
    county: "BROWARD",
    zip_codes: ["33071", "33334", "33060"],
  },
  {
    id: "mc-2",
    name: "UnitedHealthcare AARP MedicareComplete (PPO)",
    type: "MA",
    carrier: "UnitedHealthcare",
    premium_monthly: 35,
    deductible: 0,
    outOfPocketMax: 6700,
    starRating: 4.5,
    benefits: {
      primaryCare: "$5 Copay",
      specialist: "$45 Copay",
      emergencyRoom: "$90 Copay",
      urgentCare: "$35 Copay",
      rxCoverage: "$0 Tier 1-2",
      dental: "Included",
      vision: "$200/yr",
      hearing: "Included",
    },
    highlights: ["Gym membership included", "$0 Tier 1-2 Rx", "Nationwide PPO network"],
    county: "BROWARD",
    zip_codes: ["33071", "33334"],
  },
  {
    id: "mc-3",
    name: "Aetna Medicare Eagle (PPO)",
    type: "MA",
    carrier: "Aetna",
    premium_monthly: 0,
    deductible: 0,
    outOfPocketMax: 7550,
    starRating: 4.0,
    benefits: {
      primaryCare: "$0 Copay",
      specialist: "$40 Copay",
      emergencyRoom: "$100 Copay",
      urgentCare: "$40 Copay",
      rxCoverage: "$0 Tier 1",
      dental: "Basic",
      vision: "$150/yr",
      hearing: "$500/yr",
    },
    highlights: ["$0 Premium", "Part B giveback $148/mo", "OTC allowance $45/qtr"],
    county: "BROWARD",
    zip_codes: ["33071", "33334", "33060"],
  },
  {
    id: "mc-4",
    name: "Aetna Medicare Supplement Plan G",
    type: "Supplement",
    carrier: "Aetna",
    premium_monthly: 142,
    deductible: 226,
    outOfPocketMax: 0,
    starRating: 4.0,
    benefits: {
      primaryCare: "After Deductible",
      specialist: "After Deductible",
      emergencyRoom: "Covered",
      urgentCare: "Covered",
      rxCoverage: "Not Included",
      dental: "Not Included",
      vision: "Not Included",
    },
    highlights: ["Covers Part A & B gaps", "No network restrictions", "No referrals needed"],
    county: "BROWARD",
    zip_codes: ["33071", "33334", "33060"],
  },
  {
    id: "mc-5",
    name: "Cigna Achieve Medicare Supplement Plan N",
    type: "Supplement",
    carrier: "Cigna",
    premium_monthly: 118,
    deductible: 226,
    outOfPocketMax: 0,
    starRating: 3.5,
    benefits: {
      primaryCare: "$20 Copay",
      specialist: "$50 Copay",
      emergencyRoom: "Covered",
      urgentCare: "Covered",
      rxCoverage: "Not Included",
      dental: "Not Included",
      vision: "Not Included",
    },
    highlights: ["Low monthly premium", "Covers Part B excess charges", "Nationwide coverage"],
    county: "BROWARD",
    zip_codes: ["33071"],
  },
  {
    id: "mc-6",
    name: "SilverScript Choice Part D",
    type: "PartD",
    carrier: "CVS / SilverScript",
    premium_monthly: 21,
    deductible: 505,
    outOfPocketMax: 0,
    starRating: 3.5,
    benefits: {
      primaryCare: "N/A",
      specialist: "N/A",
      emergencyRoom: "N/A",
      urgentCare: "N/A",
      rxCoverage: "$0 Tier 1",
      dental: "Not Included",
      vision: "Not Included",
    },
    highlights: ["$0 Tier 1 generics", "60,000+ network pharmacies", "Mail-order available"],
    county: "BROWARD",
    zip_codes: ["33071", "33334", "33060"],
  },
];
